/*
SWFAddress Plugin v1.2.6 for KRPanoJS and iOS4.2+
by Jaydee || http://jaydee.ru/
*/
var krpanoplugin=function(){function U(){var a=c.get("xml.url");if((a=(a=a&&""!=a?a.toLowerCase():c.get("xml.scene"))&&""!=a?a.toLowerCase():null)&&u!=a){u=a;if(a=p[u]){var b=g+".pano["+a+"].",d=c.get(b+"pageurl"),f=c.get(b+"pagetitle");d&&J(d);if(f){var b=v,d=w,e=f;f.match(K)&&(e=c.get(K.exec(f)[1]));f=e;b=b?b+f:f;SWFAddress.setTitle(d?b+d:b)}h()}!1==SWFAddress.getHistory()&&SWFAddress.setHistory(!0);c.call(s(a,"onxmlcomplete"))}}function V(a,b,c){var b=L(b),f="true"==c;if(a&&""!=a&&"null"!=a){for(var e=
SWFAddress.getParameterNames(),c=[],g=0;g<e.length;g++){var j=e[g],k=SWFAddress.getParameter(j);"string"==typeof k&&(k=[k]);j==a&&(k=null===b||""==b?[]:f?k.concat([b]):[b]);for(var i=0;i<k.length;i++)c.push(j+"="+k[i])}a:{for(f=0;f<e.length;f++)if(a===e[f]){e=f;break a}e=-1}-1==e&&c.push(a+"="+b);x(c.join("&"));d["param_"+a]=b;h()}else q("setparam function syntax error!",3)}function W(){y();for(var a,b,c="",f=0;f<arguments.length;f++)b=arguments[f].split("="),a=b[0],b=b[1],a&&""!=a&&"null"!=a?((b=
L(b))&&(c+=a+"="+b+"&"),d["param_"+a]=b):q("setparams function syntax error!",3);0!=c.length&&(c=c.substr(0,c.length-1));x(c);h()}function X(){y();x(null);h()}function Y(a,b){a&&c.set(b,escape(a))}function Z(a,b){c.set(b,a.replace(/\&amp\;/gi,"&"))}function z(){var a=SWFAddress.getPath();"/"!=a&&c.call(A(B,a))}function C(){var a=SWFAddress.getPath();if(o&&(!a||""==a))a="/";if(l==D){var b="/"==a,a=!0==b?s(M,"pageurl"):a;!0==b&&!1==o&&SWFAddress.setHistory(!1);if(r[a]){var m=r[a],f=(b=s(m,"xmlurl"))&&
""!=b?"xml":"scene",b=b&&""!=b?b:s(m,"scene"),m=c.get("xml.url"),e=c.get("xml.scene");b&&(b!=m||b!=e)&&c.call(A(d.onurlchange,a,b,f))}else c.call(E)}else c.call(A(d.onurlchange,a));y();a=SWFAddress.getParameterNames();for(b=0;b<a.length;b++)d["param_"+a[b]]=SWFAddress.getParameter(a[b]);c.call(d.onparamschange);h()}function $(){q("v"+F);c.set(g+".keep",!0);c.set(g+".visible",!1);c.set(g+".handcursor",!1);o=top===self?!1:!0;d.registerattribute("version",F,function(){},function(){return F});d.registerattribute("mode",
t,function(a){l?q("The mode cannot to be changed at runtime.",3):l=a},function(){return l});d.registerattribute("isiframe",o,function(){},function(){return o});d.registerattribute("path",SWFAddress.getPath(),function(a){J(a)},function(){return SWFAddress.getPath()});d.registerattribute("title",SWFAddress.getTitle(),function(a){SWFAddress.setTitle(a)},function(){return SWFAddress.getTitle()});d.registerattribute("value",SWFAddress.getValue(),function(){},function(){return SWFAddress.getValue()});d.registerattribute("baseurl",
null,function(){},function(){return N});d.registerattribute("fullurl",null,function(){},function(){return G});d.registerattribute("fullurlescaped",null,function(){},function(){return O});d.registerattribute("querystring",null,function(){},function(){return SWFAddress.getQueryString()});d.registerattribute("hasparams",null,function(){},function(){return 0!=SWFAddress.getParameterNames().length});d.registerattribute("titleprefix",null,function(a){v=a},function(){return v});d.registerattribute("titlepostfix",
null,function(a){w=a},function(){return w});d.registerattribute("randomroot",!1,function(a){H=a},function(){return H});d.registerattribute("parsepaths",!0,function(a){I=a},function(){return I});d.registerattribute("onurlchange",null,function(a){P=a},function(){return P});d.registerattribute("onpathchange",null,function(a){B=a},function(){return B});d.registerattribute("onparamschange",null,function(a){Q=a},function(){return Q});d.registerattribute("oninvalidaddress",null,function(a){E=a},function(){return E});
l=d.mode?d.mode:t;l!=D&&l!=t&&(l=t,q("Incorrect mode specified. Plugin will run in manual mode.",3));if(l==D){p={};r={};for(var a=parseInt(c.get(g+".pano.count")),b,m,f=!0==H,e=0;e<a;e++){var n=c.get(g+".pano["+e+"].name"),j=g+".pano["+n+"].",k=c.get(j+"pageurl"),i=c.get(j+"xmlurl"),h=c.get(j+"scene"),j="true"==c.get(j+"root");if(k&&(i||h))0==e&&(m=!f?n:c.get(g+".pano["+Math.floor(Math.random()*(1+(a-1)-0)+0)+"].name")),!b&&j&&!f&&(m=n,b=!0),r[k]=n,i?(!0==I&&(i=c.parsePath(i)),i=i.toLowerCase(),p[i]=
n):h&&(h=h.toLowerCase(),p[h]=n)}M=m;d.update=U;c.set("events[swfaddress].keep",!0);c.set("events[swfaddress].onxmlcomplete",g+".update();")}d.setparam=V;d.setparams=W;d.removeparams=X;d.escape=Y;d.replaceampersands=Z;SWFAddress.addEventListener(SWFAddressEvent.EXTERNAL_CHANGE,C);SWFAddress.addEventListener(SWFAddressEvent.CHANGE,z);C(null);z(null)}function J(a){var b=SWFAddress.getQueryString();SWFAddress.setValue(a+(b?"?"+b:""))}function x(a){SWFAddress.setValue(SWFAddress.getPath()+(a?"?"+a:""))}
function R(){var a=SWFAddress.getBaseURL()+"#"+SWFAddress.getPath(),b=SWFAddress.getQueryString(),a=a+(b&&""!=b?"?"+SWFAddress.getQueryString():"");o?a=top.location.href?top.location.href:self.location.href:(b=window.location.href.toString(),b!=a&&(a=b));return a}function h(){var a=R(),b=a.indexOf("#"),b=-1==b?a.length:b;N=a.substring(0,b);G=R();O=escape(G)}function y(){for(var a in d)a.match("param_.+")&&(d[a]=null)}function L(a){if(!a)return null;var b;a&&a.match(S)?(a=S.exec(a)[1],a=c.get(a)?c.get(a):
a,b=Math.floor(a).toString()):(b=c.get(a))||(b=a);return b}function A(a,b,c,d){var e=null;a&&b&&(e=a.replace(/\%PATH/gi,b),c&&(e=e.replace(/\%PANOID/gi,c)),d&&(e=e.replace(/\%TYPE/gi,d)));return e}function s(a,b){return c.get(g+".pano["+a+"]."+b)}function q(a,b,d){b||(b=1);d||(d=!1);d&&c.call("showlog();");c.trace(b,T+": "+a)}var T="SWFAddress Plugin",F="1.2.6",D="auto",t="manual",l=null,o=!1,S=/^r\(((?:.)+)\)$/i,K=/^get\(((?:.)+)\)$/i,p=null,r=null,M=null,u=null,H=null,I=null,v=null,w=null,P=null,
B=null,Q=null,E=null,N=null,G=null,O=null,c=null,d=null,g=null;this.registerplugin=function(a,b,h){c=a;g=b;d=h;"1.0.8.14">c.version||"2011-05-20">c.build?c.trace(3,T+" - too old krpano version (min. 1.0.8.14 required)"):$()};this.unloadplugin=function(){SWFAddress.removeEventListener(SWFAddressEvent.EXTERNAL_CHANGE,C);SWFAddress.removeEventListener(SWFAddressEvent.CHANGE,z);c.set("events[swfaddress].keep",!1);c.set("events[swfaddress].onxmlcomplete",null);c=g=d=p=r=null}};